### ISSUE TITLE
1.7.10 Incompatibility with Twilight Forest

### ISSUE THREAD

**Issue by glowredman** [tr7zw/EntityCulling#145]
Probably similar to #144.

```
java.lang.ClassCastException: class twilightforest.client.renderer.entity.RenderTFTinyFirefly cannot be cast to class dev.tr7zw.entityculling.mixin.RenderLivingEntityAccessor (twilightforest.client.renderer.entity.RenderTFTinyFirefly and dev.tr7zw.entityculling.mixin.RenderLivingEntityAccessor are in unnamed module of loader 'RFB-Launch' @247d8ae)
	at RFB-Launch//net.minecraft.client.renderer.entity.RenderManager.handler$zbf000$entityculling$doRenderEntity(RenderManager.java:531)
	at RFB-Launch//net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java)
	at RFB-Launch//net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:291)
	at RFB-Launch//net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:264)
	at RFB-Launch//net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:737)
	at RFB-Launch//net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1712)
	at RFB-Launch//net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1392)
	at RFB-Launch//net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at RFB-Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:7506)
	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:148)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at RFB-System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219)
```

**Comment by tr7zw** [comment]
Yea it's basically the same issue, just on a different entity. Weird that 1.7 mods use that many clientside entities and that they somehow don't get Mixin-d correctly.
