### ISSUE TITLE
Mod entityculling provides a broken implementation of ModMenuApi - V 1.20.5

### ISSUE THREAD

**Issue by Tiegertosch** [tr7zw/EntityCulling#150]
Works as always, just produces this error message when starting the game.

```
[11:08:12] [Render thread/ERROR]: Mod entityculling provides a broken implementation of ModMenuApi
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'modmenu' provided by 'entityculling'
    at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.15.10.jar:?]
    at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:79) ~[modmenu-10.0.0-beta.1.jar:?]
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
    at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:75) ~[modmenu-10.0.0-beta.1.jar:?]
    at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) [fabric-loader-0.15.10.jar:?]
    at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) [fabric-loader-0.15.10.jar:?]
    at net.minecraft.class_310.<init>(class_310.java:484) [client-intermediary.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:223) [client-intermediary.jar:?]
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: none
    at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[fabric-loader-0.15.10.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.10.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.10.jar:?]
    ... 13 more
Caused by: java.lang.ClassNotFoundException: none
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
    at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.10.jar:?]
    at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.10.jar:?]
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
    at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
    at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
    at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
    at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.15.10.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.10.jar:?]
    at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.10.jar:?]
    ... 13 more
```

**Comment by tr7zw** [comment]
Correct. I use my own tools to generate the build system and files like the fabric.mod.json. Recently I extended that build system to build 1.16.5-1.20.5 fabric/forge/neoforge all from the same source code, and when setting this up and porting most projects to it, assumed that all mods have a config screen. EntityCulling wasn't yet ported to the new build system, so when 1.20.5 rolled out, I just quickly ported it over just for the 1.20.5 fabric release, setting the configscreen provider class to "none". This error is caused by that, but this doesn't have any other side effects. Once Forge/NeoForge are ready, I'll fully port this repo to the build system with 1.16.5-1.20.5 in the same codebase, and fix this issue(either add a config screen for the mod, or add a way to the template to not set one).
