### ISSUE TITLE
[compatibility] 1.20.6: Fabric Tailor

### ISSUE THREAD

**Issue by MeeniMc** [tr7zw/EntityCulling#155]
**Describe the bug**

Error messages are generated in the log about 'out of bound access', usually that will cause bugs but  I didn't see something egregious atm. 

```
[12:29:40] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2586.method_11017()" because the return value of "java.util.Map$Entry.getValue()" is null
[12:29:40] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.cullBlockEntities(CullTask.java:148)
[12:29:40] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:69)
[12:29:40] [CullThread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[12:32:27] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException
```

```
[12:37:40] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException
[12:37:46] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException: Cannot invoke "dev.tr7zw.entityculling.versionless.access.Cullable.isForcedVisible()" because "cullable" is null
[12:37:46] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.cullBlockEntities(CullTask.java:155)
[12:37:46] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:69)
[12:37:46] [CullThread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[12:37:47] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.ArrayIndexOutOfBoundsException: Index 152 out of bounds for length 129
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap$MapIterator.nextEntry(Object2ObjectLinkedOpenHashMap.java:1156)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap$EntryIterator.next(Object2ObjectLinkedOpenHashMap.java:1267)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap$EntryIterator.next(Object2ObjectLinkedOpenHashMap.java:1249)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.cullBlockEntities(CullTask.java:142)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:69)
[12:37:52] [CullThread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[12:37:53] [CullThread/INFO] (Minecraft) [STDERR]: java.lang.NullPointerException
```

**To Reproduce**

1. 1.20.6 fabric
2. Install Fabric Tailor 2.4.1
3. Install Entity Culling 1.6.4
4. Error may spit out during gameplay, may take a while

*Are you using any other mods?*

Can reproduce with only Entity Culling and Fabric Tailor (and dependencies like fabric api).

**Sister issue**

https://github.com/samolego/FabricTailor/issues/102

**Comment by tr7zw** [comment]
Doubt that FabricTailor has anything to do with that. That message can happen on its own and is not an issue(it happens by design).
