### ISSUE TITLE
NullPointerException triggered

### ISSUE THREAD

**Issue by d-faure** [tr7zw/EntityCulling#29]
https://github.com/tr7zw/EntityCulling-Fabric/blob/b29646e3b34ed87da6ca3e3e574056250dd07363/src/main/java/dev/tr7zw/entityculling/CullTask.java#L103

```
[11:57:51] [CullThread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "dev.tr7zw.entityculling.access.Cullable.isForcedVisible()" because "cullable" is null
[11:57:51] [CullThread/INFO]: [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:103)
[11:57:51] [CullThread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)```

**Comment by tr7zw** [comment]
Eh what other kinds of mods do you use? And can you send a full log.

**Comment by d-faure** [comment]
Here you are: https://paste.ee/p/lvsdK

**Comment by tr7zw** [comment]
I guess this is a race condition happening on world load. It doesn't crash the culling or anything, but I will fix it in the next release to prevent confusion.

**Comment by d-faure** [comment]
In fact it occurred _during the game_ as I was rushing away from a skeleton, looking around quickly to a better position and counterattack.
I also found this exception triggering rather weird since you were explicitly catching it. Perhaps it came as I finally killed the monster, and therefore invalidate the reference. I don't know.

**Comment by OS-Void** [comment]
```
[04:28:53] [CullThread/INFO]: [STDERR]: java.lang.NullPointerException: Cannot invoke "dev.tr7zw.entityculling.access.Cullable.isForcedVisible()" because "cullable" is null
[04:28:53] [CullThread/INFO]: [STDERR]: 	at dev.tr7zw.entityculling.CullTask.run(CullTask.java:103)
[04:28:53] [CullThread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

I'm also getting it from time to time without a crash, but shows in the logs.

Mods:
	- architectury@2.0.11
	- betterbeds@1.2.0
	- cullleaves@2.2.0
	- entityculling@1.3.0
	- fabric@0.36.0+1.17
	- fabricloader@0.11.6
	- hydrogen@0.3
	- inventoryhud@3.3.2
	- inventorysorter@1.7.9-1.17
	- kyrptconfig@1.1.10-1.17
	- lazydfu@0.1.2
	- litematica@0.0.0-dev.20210616.033538
	- lithium@0.7.2-SNAPSHOT
	- malilib@0.10.0+dev.22
	- modmenu@2.0.2
	- roughlyenoughitems@6.0.258-alpha
	- smoothboot@1.16.5-1.6.0
	- sodium@0.3.0+rev.8910694-dirty
	- starlight@fabric-1.0.0-RC2-3a77ed1
